### ISSUE TITLE
IllegalArgumentException when using OWL model

### ISSUE THREAD

**Issue by mommi84** [mommi84/Mandolin#11]
Probably due to 0 clauses collected from the `factors` table.
```
Exception in thread "main" java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388)
	at com.googlecode.rockit.app.sampler.gibbs.GIBBSSampler.sample(GIBBSSampler.java:154)
	at org.aksw.mandolin.inference.RockitGibbsSampling.gibbsSampling(RockitGibbsSampling.java:74)
	at org.aksw.mandolin.inference.ProbKBToRockitGibbsSampling.infer(ProbKBToRockitGibbsSampling.java:67)
	at org.aksw.mandolin.Mandolin.run(Mandolin.java:103)
	at org.aksw.mandolin.Mandolin.main(Mandolin.java:154)
```

**Comment by mommi84** [comment]
Reason: rules do not contain the aim property. Simply catch the exception.

**Comment by mommi84** [comment]
Bash output:
```
$ /usr/local/Cellar/postgresql/9.4.1/bin/psql probkb -f /Users/tom/PhD/srl/Mandolin/eval/0001/load.sql
SET
SET
COPY 13
COPY 2270
COPY 14
COPY 2795
COPY 14
COPY 0
psql:/Users/tom/PhD/srl/Mandolin/eval/0001/load.sql:18: ERROR:  invalid input syntax for integer: ""
CONTEXT:  COPY extractions, line 5177, column rel: ""
SELECT 0
CREATE INDEX
CLUSTER
DELETE 0
 qc 
----
  0
(1 row)

psql:/Users/tom/PhD/srl/Mandolin/eval/0001/load.sql:37: ERROR:  invalid input syntax for integer: ""
CONTEXT:  COPY mln1, line 2, column body: ""
COPY 4
psql:/Users/tom/PhD/srl/Mandolin/eval/0001/load.sql:39: ERROR:  invalid input syntax for integer: ""
CONTEXT:  COPY mln3, line 9, column body1: ""
psql:/Users/tom/PhD/srl/Mandolin/eval/0001/load.sql:40: ERROR:  invalid input syntax for integer: ""
CONTEXT:  COPY mln4, line 13, column body2: ""
COPY 6
psql:/Users/tom/PhD/srl/Mandolin/eval/0001/load.sql:42: ERROR:  invalid input syntax for integer: ""
CONTEXT:  COPY mln6, line 10, column body2: ""
ANALYZE
ANALYZE
ANALYZE
ANALYZE
ANALYZE
ANALYZE
ANALYZE
```
